/**
 * API for Contact App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @springdoc.version@
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContactViewList {
    /**
     * Aggregated information: company name, lastname, firstname
     */
    name?: string;
    /**
     * The id of the contact
     */
    id?: number;
    /**
     * The thumbnail of the contact
     */
    thumbNail?: string;
    /**
     * Aggregated group id\'s
     */
    groupsIdAggregate?: string;
    /**
     * Aggregated relations id\'s
     */
    relationsIdAggregate?: string;
    /**
     * The birth date of the contact
     */
    birthDate?: string;
    /**
     * Aggregated phone numbers
     */
    phonesAggregate?: string;
    /**
     * Aggregated email adresses
     */
    addressesAggregate?: string;
    /**
     * Aggregated email addresses
     */
    emailsAggregate?: string;
    /**
     * The last or surname name of the contact
     */
    lastName?: string;
    /**
     * The company of the contact
     */
    company?: string;
    /**
     * The content type like image/jpeg or image/png of the thumbnail or photo
     */
    photoContentType?: string;
    /**
     * The first name of the contact
     */
    firstName?: string;
}

