/**
 * API for Contact App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: @springdoc.version@
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Contact } from './contact';


export interface ContactRelation { 
    id?: number;
    contactRelationType?: ContactRelation.ContactRelationTypeEnum;
    contactRelationValue?: string;
    contacts?: Set<Contact>;
    usage?: number;
}
export namespace ContactRelation {
    export type ContactRelationTypeEnum = 'CUSTOMER' | 'CREDITOR' | 'COLLEAGUES' | 'AUTORITY' | 'MEDICAL' | 'OTHERS' | 'FAMILIY' | 'FRIENDS';
    export const ContactRelationTypeEnum = {
        Customer: 'CUSTOMER' as ContactRelationTypeEnum,
        Creditor: 'CREDITOR' as ContactRelationTypeEnum,
        Colleagues: 'COLLEAGUES' as ContactRelationTypeEnum,
        Autority: 'AUTORITY' as ContactRelationTypeEnum,
        Medical: 'MEDICAL' as ContactRelationTypeEnum,
        Others: 'OTHERS' as ContactRelationTypeEnum,
        Familiy: 'FAMILIY' as ContactRelationTypeEnum,
        Friends: 'FRIENDS' as ContactRelationTypeEnum
    };
}


